Added file retry_decor.py
VaretsaK/homework pull request #13
Opened 2023-03-14 11:22 UTC by VaretsaK

2023-03-20 07:59 UTC, vladyslavushakovten requested changes

2023-03-20 07:59 UTC, vladyslavushakovten commented on retry_decor.py
> +                except exc:
Тут відловлювати потрібно всі помилкими

2023-03-20 07:59 UTC, vladyslavushakovten commented on retry_decor.py
> +            print(exc.__name__)
тут потрібно робити raise exc

2023-03-21 17:21 UTC, VaretsaK commented on retry_decor.py
> +                except exc:
Додав

2023-03-21 17:21 UTC, VaretsaK commented on retry_decor.py
> +            print(exc.__name__)
Змінив

2023-03-29 10:02 UTC, vladyslavushakovten approved these changes

2023-03-30 07:09 UTC, merged