Added file game_xo.py
VaretsaK/homework pull request #28
Opened 2023-04-04 19:03 UTC by VaretsaK

2023-04-10 14:22 UTC, vladysllav requested changes
Декілька маленьких коментарів

2023-04-10 14:22 UTC, vladysllav commented on game_xo.py
> +            if self.__game_field[row - 1][column - 1] not in "XO":
Я б спочатку намагався отримати значення [row-1] і так далі, і відловлював помилкиґ. бо я можу ввести і 10, ти це не перевіряєшь

2023-04-10 14:22 UTC, vladysllav commented on game_xo.py
> +                self.winner_columns()
Тут краще створити 1 функцію, яка буде перевіряти на кінець гри. А вссередині її вже перевіряй функціями або як зочешь на рядок, стовпець та все інше

2023-04-10 20:02 UTC, VaretsaK commented on game_xo.py
> +            if self.__game_field[row - 1][column - 1] not in "XO":
Зробив трішки інакше, шоб без помилок обходитись. Чи краще все ж таки відловлювати? Бо мені весь блок If (або майже весь) доведеться в try покласти

2023-04-12 05:03 UTC, vladysllav approved these changes

2023-04-12 19:50 UTC, merged