Added file convert_error.py
VaretsaK/homework pull request #4
Opened 2023-03-09 17:38 UTC by VaretsaK

2023-03-13 07:55 UTC, vladyslavushakovten requested changes
Залишив коментар

2023-03-13 07:55 UTC, vladyslavushakovten commented on convert_error.py
> +    return int(number)
Чему не повертаєшь number? Або чому одразу не конвертуешь до інта?

2023-03-13 14:36 UTC, VaretsaK commented on convert_error.py
> +    return int(number)
Вніс зміни

2023-03-19 09:06 UTC, vladyslavushakovten approved these changes

2023-03-19 10:06 UTC, merged