Added a new directory with file few_exceptions
VaretsaK/homework pull request #5
Opened 2023-03-09 20:26 UTC by VaretsaK

2023-03-14 03:53 UTC, vladyslavushakovten requested changes

2023-03-14 03:53 UTC, vladyslavushakovten commented on file_with_few_exceptions/few_exceptions.py
> +    file = open("divisor.txt", "w")
Не потрібно завжди відкривати файли, роби це один раз і передавай обʼєкт файлу до функції

2023-03-14 03:53 UTC, vladyslavushakovten commented on file_with_few_exceptions/few_exceptions.py
> +        try:
Не дуже хороша практика робити іерархію трай блоків, краще робити декілька ексепт блоків з різними типами помилок

2023-03-14 03:53 UTC, vladyslavushakovten commented on file_with_few_exceptions/few_exceptions.py
> +            file.close()
Відкривай файл окремо, і передавай до функції

2023-03-14 20:02 UTC, VaretsaK commented on file_with_few_exceptions/few_exceptions.py
> +            file.close()
Переписав код

2023-03-19 09:04 UTC, vladyslavushakovten approved these changes

2023-03-19 10:07 UTC, merged